version: '3.8'

services:
  redis-master:
    image: redis/redis-stack-server:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--save", "60 1", "--protected-mode", "no"]
    networks:
      - redis-net

  redis-replica:
    image: redis/redis-stack-server:latest
    container_name: redis-replica
    ports:
      - "6380:6379"  # Expondo a porta do Redis replica
    command: ["redis-server", "--appendonly", "yes", "--save", "60 1", "--replicaof", "redis-master", "6379", "--protected-mode", "no"]
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
